= R5.A.08 -- Dépôt pour les TPs
Hugo Wendjaneh
:icons: font
:MoSCoW: https://fr.wikipedia.org/wiki/M%C3%A9thode_MoSCoW[MoSCoW]

Ce dépôt concerne les rendus de mailto:A_changer@etu.univ-tlse2.fr[Jonh Doe].

== TP1

.Code is_it_friday_yet.feature
[source,gherkin]
---
# language: en

Feature: Is it Friday yet?
  Everybody wants to know when it's Friday

  Scenario Outline: Sunday isn't Friday
    Given today is "<day>"
    When I ask whether it's Friday yet
    Then I should be told "<answer>"
  
  Examples:
  | day            | answer |
  | Friday         | TGIF   |
  | Sunday         | Nope   |
  | anything else! | Nope   |
---

.Code IsItFridayYetTest.java
[source,java]
---
package hellocucumber;

import static org.junit.jupiter.api.Assertions.assertEquals;

import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

/**
 * IsItFriday
 */
public class IsItFriday {
    private String today;
    private String actualAnswer;

    static String isItFriday(String today) {
        return "Friday".equals(today) ? "TGIF" : "Nope";
    }

    @Given("today is {string}")
    public void today_is_sunday(String pfToday) {
        today = pfToday;
    }

    @When("I ask whether it's Friday yet")
    public void i_ask_whether_it_s_friday_yet() {
        actualAnswer = IsItFriday.isItFriday(today);
    }

    @Then("I should be told {string}")
    public void i_should_be_told(String expectedAnswer) {
        assertEquals(expectedAnswer, actualAnswer);
    }

}
---


.Résultat mvn test
[source, bash]
---
11:01:25 furiza@mirabelle /home/furiza/school/BehaviorDrivenDevelopment/tp1/r5-a-08-qualdev-Furiza31/hellocucumber [0] (main)
-> mvn test
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< hellocucumber:hellocucumber >---------------------
[INFO] Building hellocucumber 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hellocucumber ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/furiza/school/BehaviorDrivenDevelopment/tp1/r5-a-08-qualdev-Furiza31/hellocucumber/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.11.0:compile (default-compile) @ hellocucumber ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hellocucumber ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.11.0:testCompile (default-testCompile) @ hellocucumber ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:3.2.2:test (default-test) @ hellocucumber ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running hellocucumber.RunCucumberTest

Scenario: The example                       # hellocucumber/example.feature:3
  Given an example scenario                 # hellocucumber.StepDefinitions.anExampleScenario()
  When all step definitions are implemented # hellocucumber.StepDefinitions.allStepDefinitionsAreImplemented()
  Then the scenario passes                  # hellocucumber.StepDefinitions.theScenarioPasses()

Scenario Outline: Sunday isn't Friday # hellocucumber/is_it_friday_yet.feature:13
  Given today is "Friday"             # hellocucumber.IsItFriday.today_is_sunday(java.lang.String)
  When I ask whether it's Friday yet  # hellocucumber.IsItFriday.i_ask_whether_it_s_friday_yet()
  Then I should be told "TGIF"        # hellocucumber.IsItFriday.i_should_be_told(java.lang.String)

Scenario Outline: Sunday isn't Friday # hellocucumber/is_it_friday_yet.feature:14
  Given today is "Sunday"             # hellocucumber.IsItFriday.today_is_sunday(java.lang.String)
  When I ask whether it's Friday yet  # hellocucumber.IsItFriday.i_ask_whether_it_s_friday_yet()
  Then I should be told "Nope"        # hellocucumber.IsItFriday.i_should_be_told(java.lang.String)

Scenario Outline: Sunday isn't Friday # hellocucumber/is_it_friday_yet.feature:15
  Given today is "anything else!"     # hellocucumber.IsItFriday.today_is_sunday(java.lang.String)
  When I ask whether it's Friday yet  # hellocucumber.IsItFriday.i_ask_whether_it_s_friday_yet()
  Then I should be told "Nope"        # hellocucumber.IsItFriday.i_should_be_told(java.lang.String)
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.150 s -- in hellocucumber.RunCucumberTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.419 s
[INFO] Finished at: 2023-12-11T11:01:58+01:00
[INFO] ------------------------------------------------------------------------
---